title: VT Yucatan Brain Template
logo: /assets/images/VT.jpeg
description:
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

github:
  repository_url: https://github.com/lacontelab/VT-Yucatan-MRI-Template
  paper_url: https://www.biorxiv.org/content/10.1101/2020.07.17.209064v1
  tar_url: https://github.com/lacontelab/VT-Yucatan-MRI-Template/releases/download/v0.1.0/VT_Yucatan_MRI_templates_v0.1.tar.gz

